# .github/workflows/deploy.yml

name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v2
        with:
          resource-group: project20-rsrcgrp
          cluster-name: project20-aks

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/template.yml
          kubectl apply --validate=false -f kubernetes/test.yml
